### ISSUE TITLE
CovPass App iOS - Generated EU print pdf contains no QR-Code.

### ISSUE THREAD

**Issue by Ron-70** [Digitaler-Impfnachweis/covpass-ios#104]
## Technical details

- Device name: iPhone 6
- OS version: iOS 12.5
- App version: CovPass App Version 1.15 and 1.16

## Description

Generated pdf files of EU prints don't contain any QR-Code with a certificate.

Screen extract of generated pdf using iPhone 6 running iOS 12.5:
 ![grafik](https://user-images.githubusercontent.com/52568084/150100930-ba5c14b1-cb59-4570-9025-859a50c3e627.png)

I used Preview App of OSX and Adobe Acrobat Reader on Windows 10 to display the pdf after generation. Both show no QR-Code within the pdf.

## Steps to reproduce the issue

Select "EU-Ausdruck erstellen" (EU print) and generate the pdf. 

## Expected behaviour

Pdf of EU print with a valid QR-Code.

## Possible Fix

Probably a problem with the base64 encoded QR code image inside the SVG template and rendering it on the WKWebView for export as pdf in iOS 12.5.

**Comment by Ein-Tim** [comment]
Can't reproduce under iOS 15.2.1 on an iPhone XR with the latest version of CovPass.

**Comment by Ron-70** [comment]
Hi @Ein-Tim,

please check my just added "Possible Fix" analysis.

**Comment by Ein-Tim** [comment]
@Ron-70 

I saw it but just wanted to confirm your guess that this is iOS 12 only (-:

**Comment by Ron-70** [comment]
I just changed the "Possible Fix" analysis because the doubted generateQRCode() function is working on other places within the app.

**Comment by timokoenig** [comment]
@Ron-70 does this happen with all of your certificates?

**Comment by Ron-70** [comment]
> @Ron-70 does this happen with all of your certificates?

Yes, for all of my 3 available certificates the generated pdfs contain no QR-Code.

**Comment by timokoenig** [comment]
@Ron-70 ok thanks, just wanted to make sure that there aren't any other problems

**Comment by Kurt57** [comment]
Hi @Ron-70 i have created an internal ticket to solve this problem. But can you even reproduce this issue?

**Comment by Ron-70** [comment]
> Hi @Ron-70 i have created an internal ticket to solve this problem. But can you even reproduce this issue?

I just updated to CovPass App version 1.22.1 and it's still the same issue. For all of my 3 available certificates the generated pdfs contain no QR-Code. (iPhone 6 / iOS 12.5)

**Comment by Kurt57** [comment]
Hi @Ron-70  we have fixed something else there, may be that also helps with your problem? Do you have any update for us?

**Comment by Ron-70** [comment]
Hi @Kurt57,

I just installed the latest available version 1.28(2) and the generated pdf still doesn't contain the QR code.

**Comment by xhgr999** [comment]
I can confirm this still happening as of today on latest CovPass App version 1.41 (2)  on iOS 12.5.7.
The generated PDF does not contain a QR code, looking exactly like the screenshot in the description.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
