### ISSUE TITLE
Vaccination Certificate Detail shows "Entry rules" for Country Vaccinating

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#146]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The vaccination detail view shows "Germany - Entry rules" for "Land der Impfung / Country vaccinating". This seems to be the problem that the detail view uses the same country list as the "Check Validity for Travel" feature.

## Steps to reproduce the issue

1. Import Vaccination Certificate from Germany
2. Go to certificate details
3. Look at the "Country Vaccinating"

## Expected behaviour

The field should not show "Entry Rules".

**Comment by Kurt57** [comment]
This is already fixed in the prepared version. But one more, in the cert detail if you go over rules check, is still there. But will also soon fixed.

**Comment by Kurt57** [comment]
@timokoenig can be closed?

**Comment by timokoenig** [comment]
Cert Detail for the Rule Check still shows the "Entry Rules" text

**Comment by Kurt57** [comment]
ok lets keep this open for that also

**Comment by Ein-Tim** [comment]
@timokoenig Maybe I'm missing something but I don't see this problem anymore, do you?

**Comment by timokoenig** [comment]
@Ein-Tim if you go on "Check Validity" and then click on your certificate, you will see the text "Entry Rules" together with the country

**Comment by Ein-Tim** [comment]
Ah yes,  I missed that, sorry.

**Comment by timokoenig** [comment]
Seems to be fixed.
